### ISSUE TITLE
how to set custom video capture size, framerate, keyframe interval, bitrate ?

### ISSUE THREAD

**Issue by gstream** [daniulive/SmarterStreaming#10]

**Comment by gstream** [comment]
Thanks for providing this great library. I've tried to use this library for my video conference project (iOS & Android). 

I am using wowza media engine for server and finished configurations.

I've tried to use your demo but it has so long delay (over 5s) .

I think video conference should have low latency (less than 2 secs).

I've tried to change the video resolution option of your library but seems not working or not show difference for eyes.

I think your library is capturing high resolution video even it has low option. also not sure if it can automatically set interval, bitrate for network conditions.

Hope to hearing from you.
Regards,

**Comment by daniulive** [comment]
Hi gstream,

Thank you for the feedback.
With daniulive's player and publisher, from our side, the latency is about 1s, which is reasonable.
From your testing, do you use our player and publisher at the same time? or only use publisher?

Please provide the logs if you could reproduce the long latency with our player and publisher.
Also you could directly contact me via 89030985@qq.com

Thanks.

**Comment by daniulive** [comment]
Any update from your side?

I'll close the issue first, if still have issues, please contact 89030985@qq.com directly.
