### ISSUE TITLE
是否有在Linux环境下运行的版本

### ISSUE THREAD

**Issue by magicgw0928** [daniulive/SmarterStreaming#101]
如果要在Linux上推流，是否有在Linux环境下运行的SDK版本？如果商用付费的话，是否能定制开发Linux版本的SDK？

**Comment by daniulive** [comment]
Linux平台，目前，我们有做转发（RTSP转推RTMP，RTMP转推RTMP）、录像模块。
针对RTMP推送的场景，我们目前还没加进来采集编码部分。
具体你可以加我QQ 89030985
