### ISSUE TITLE
请问您这是开源的吗

### ISSUE THREAD

**Issue by sunqimin09** [daniulive/SmarterStreaming#12]
rt

**Comment by daniulive** [comment]
No, for more information, please refer to https://github.com/daniulive/SmarterStreaming/wiki/%E5%A4%A7%E7%89%9B%E7%9B%B4%E6%92%AD%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88.

Thanks.
