### ISSUE TITLE
Android 4.1.2 (Device mi1s) camera record crash 

### ISSUE THREAD

**Issue by yyls1992** [daniulive/SmarterStreaming#13]
The follow is crash stack:

03-10 07:38:21.539: E/AndroidRuntime(2328): FATAL EXCEPTION: main
03-10 07:38:21.539: E/AndroidRuntime(2328): java.lang.ExceptionInInitializerError
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at java.lang.Class.newInstanceImpl(Native Method)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at java.lang.Class.newInstance(Class.java:1319)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2366)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at android.app.ActivityThread.access$1600(ActivityThread.java:137)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at android.os.Looper.loop(Looper.java:137)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at android.app.ActivityThread.main(ActivityThread.java:4819)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at java.lang.reflect.Method.invoke(Method.java:511)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at dalvik.system.NativeStart.main(Native Method)
03-10 07:38:21.539: E/AndroidRuntime(2328): Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: load_library[1093]: Library 'libSmartPublisher.so' not found
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at java.lang.Runtime.load(Runtime.java:340)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at java.lang.System.load(System.java:521)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	at com.daniulive.smartpublisher.BackgroudService.<clinit>(BackgroudService.java:120)
03-10 07:38:21.539: E/AndroidRuntime(2328): 	... 13 more

Android 4.4(H60-L11) and Android 5.1(mi 4c) is ok.

**Comment by daniulive** [comment]
Please contact me via QQ 89030985
Thanks.
