### ISSUE TITLE
Android SmartPublisher 切换摄像头代码在哪儿？

### ISSUE THREAD

**Issue by HuanjunKong** [daniulive/SmarterStreaming#15]
代码里没有切换摄像头的实现，git的apk里却有。想问下具体实现在哪儿？

**Comment by daniulive** [comment]
class SwitchCameraListener implements OnClickListener
    {
        public void onClick(View v)
        {    
        	Log.i(TAG, "Switch camera..");
        	 try {
                 switchCamera();
             } catch (IOException e) {
                 // TODO Auto-generated catch block
                 e.printStackTrace();
             }
         }
    };
