### ISSUE TITLE
不是不依赖第三方框架吗?为什么iOS的SDK里面有GPUImage?

### ISSUE THREAD

**Issue by WangYng** [daniulive/SmarterStreaming#17]
不是不依赖第三方框架吗?为什么SDK里面有GPUImage?而且还不改名加前缀,加入工程全是GPUImage的冲突.这些就不说了.关键是GPUImage里面有Bug,我还不能用你们SDK里面的GPUImage..我真的服了!!!!

**Comment by daniulive** [comment]
Hi,

It's a known topic that our SDK include GPUImage in IOS platform, since we're not the expert with the beauty related field.

You could add my QQ 89030985 for further cooperation.
