### ISSUE TITLE
How to setup the SmarterStreaming for iOS?

### ISSUE THREAD

**Issue by letien91** [daniulive/SmarterStreaming#18]
I downloaded your project and I tried to run the example. It is very good.
But when I tried to add your lib in to my project. I added the neccesssary library. But It always say: 
```
[SmartPlayerSDK] lic vefify failed!
SmartPlayerSDK call SmartPlayerInitPlayer failed, ret=1
```
<img width="566" alt="library" src="https://cloud.githubusercontent.com/assets/4746055/25374857/2bce03b8-29c9-11e7-84bd-7d0972326c79.png">

Is there any special setup? Please let me know.
Thank you!

**Comment by daniulive** [comment]
It caused by license check failed.
For commercial support, please contact 89030985@qq.com.

**Comment by daniulive** [comment]
You could use our app-name in Info.plist setting as below:

<key>CFBundleName</key>
<string>SmartiOSPlayer</string>

**Comment by letien91** [comment]
Thanks for your support.
I changed the bundleName and It worked.

Thank you!
