### ISSUE TITLE
[iOS] App is frozen when the rtmp link is not been publisher

### ISSUE THREAD

**Issue by letien91** [daniulive/SmarterStreaming#19]
Hi. I tried to play a random rtmp link. But that link is not been publisher. Then I back to previous screen. App is frozen and it said
```
SmartPlayerIOS [I] Run into IOSPlayer::Stop()..
SmartPlayerIOS [I] RtmpSource::stop thread->stop+
```

**Comment by daniulive** [comment]
Hi, 

It caused by in-correct operation for you:

When press "推流", if you want to quit it, you should press "停止" before you do "返回".

IF still has issues, please contact QQ 89030985 for further support.
