### ISSUE TITLE
JAVA层不能适配所有设备

### ISSUE THREAD

**Issue by mywitness** [daniulive/SmarterStreaming#20]
1.  ##  如题，在openCamera(int type)中所做处理并不能适配所有的设备：
   某设备上只接一个USB camera，在openCamera(int type)中虽然能够判断出是前置还是后置摄像头，但Camera.open(frontIndex);或Camera.open(backIndex);中frontIndex或者backIndex值可能会与当前要打开camera的ID不对应，初始化mCamera失败，**最终导致RuntimeException: getParameters failed (empty parameters)**
既然都已经判断出是前置还是后置摄像头，这样不是更好？Camera.open(CameraInfo.CAMERA_FACING_FRONT);

2.  ##  mPreviewRunning这个变量并没有完全与实际状态同步
3.  ##  mCamera释放完了没写mCamera = null，你初始化条件是
`if (mCamera == null) {
                    mCamera = openCamera(currentCameraType);
                }`
如果当前activity的启动模式是单例呢？是不是就不能再初始化了？

**Comment by daniulive** [comment]
Thank you very much for the kindly suggestion.

**Comment by mywitness** [comment]
-。-

**Comment by mywitness** [comment]
-。-
