### ISSUE TITLE
WebRTC支持

### ISSUE THREAD

**Issue by Cheedoong** [daniulive/SmarterStreaming#22]
WebRTC已成为国际标准，是未来在线流媒体、视频直播、视频会议的趋势。
另外，其自带的Opus是公认世界上最好的音频Codec。
建议增加对WebRTC协议栈的支持，包括RTP、SRTP（媒体通道）和SCTP（任意数据通道）。

**Comment by daniulive** [comment]
Hi Cheedoong,

非常感谢您的建议，我们会根据产品规划，根据市场需求，做些调整。

Thank you.

**Comment by daniulive** [comment]
如果还有其他问题，请加我QQ 89030985 
Thank you.
