### ISSUE TITLE
平板设备录屏推流运行出错

### ISSUE THREAD

**Issue by likealeodog** [daniulive/SmarterStreaming#23]
你好，我的两个华硕平板，都是intel处理器，在使用SmartServicePublishSDKDemo时，使用了屏幕推送，不管硬编码还是软编码只要点击开始推流就运行崩溃。主要错误日志如下：
dlopen("libSmartPublisher.so", RTLD_LAZY) failed: dlopen failed: "libSmartPublisher.so" has unexpected e_machine: 40
java.lang.UnsatisfiedLinkError: dlopen failed: "libSmartPublisher.so" has unexpected e_machine: 40
	at com.daniulive.smartpublisher.BackgroudService.<clinit>(BackgroudService.java:120)
在小米4上运行正常。然后就是AS上并没有这个工程，只有相机推送和播放Demo没有录屏的AS工程？
还有就是我看到您的录屏数据处理是用的ImageReader图像数据解析发送的形式，而没有用MediaCodec配合Surface缓冲区同步异步视频数据处理的方式，我猜测可能会为了软编码和多格式支持的缘故，不知道您有没有使用过这种方式。如果使用过我想请教一下在屏幕数据没有变化时，根据内部的编码算法，同步异步两种方式，所传输的视频帧数据量都很小，而如果传输层有buffer存在的话，就会导致视频帧数据不会立即传输播放端也就有延迟的问题，您有没有好的方法或者建议去处理这个问题呢？感谢

**Comment by mywitness** [comment]
正好看到，回复楼上：
1、想要mediaCodec配合Surface缓冲做的话，mediacodec目前好像只能支持MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface，而这个出来的数据是原生的YUV。不管是我之前调通官方Camera2录像崩溃的那个Demo，还是现在用的OpenCV，要使用MediaCodec的缓冲从Camera获取数据，就必须使用COLOR_FormatSurface。如果出来的数据有多个处理，那分两个及以上的流缓冲的话一些机器会很卡。ImageReader做的是传一帧一帧数据，不会立即传播也是因为要等到当前帧数据全拿到了才会回调，这个确实会有延迟，但如果把格式做成YUV_420_888，这个过程可以变得相对较快。
2、这个错误，要么是大牛没给.so，要么就是你没正确导入（配置）吧。

**Comment by daniulive** [comment]
Hi, likealeodog,

你这个问题，是我们早期demo里面，load so的时候写法的问题，推送屏幕的demo，一直没改过，请换成如下写法：

`	static {  
		System.loadLibrary("SmartPublisher");
	}`

如果还有问题，请加我QQ 89030985

**Comment by daniulive** [comment]
Hi mywitness,

非常感谢您的回复。
我们是通用的SDK，考虑到android机型的复杂性，我们没有用最讨巧的mediacodec和surface绑定的方式，如果分辨率不高，好多情况下，软编码更合适、机型适配更好一些。
关于您提到的ImageReader，说的不错，实际上，也有做法，可以在上层启个线程，ImageReader拿到的数据，先塞到个队列里面，对底层下发的数据，从这个新的线程传下去，比如，如果隔100-200ms拿不到新的数据，可以把最后一帧数据丢下去，保证连续性。

Thanks you.

**Comment by likealeodog** [comment]
嗯 的确是写法问题 已经解决了 感谢！也谢谢上面回答的
