### ISSUE TITLE
这个支持实时录屏功能吗？比如说我在玩手机游戏的时候，把我的手机实时录屏然后推流？

### ISSUE THREAD

**Issue by kobe1941** [daniulive/SmarterStreaming#24]

**Comment by daniulive** [comment]
Android 5.0以上可以支持录屏，我们有相关的demo。
iOS考虑到权限问题，我们没有提供，如果你们能拿到屏幕的原始数据，可以调用我们YUV、RGB或者，编码后的H264接口，和我们的系统对接。

**Comment by daniulive** [comment]
Closed.

If any further requests, please contact me directly.

QQ 89030985
