### ISSUE TITLE
传入I420的视频数据问题

### ISSUE THREAD

**Issue by xiaoqiu1235** [daniulive/SmarterStreaming#27]
错误信息：OnI420Frame yStride is error, yStride=4, org_width_=1920
代码：daniuPublish.SmartPublisherOnCaptureVideoI420Data(data,data.length,4,2,0);

**Comment by daniulive** [comment]
你可能对I420格式不太了解：

 /**
	* Set live video data(no encoded data).
	*
	* @param data: I420 data
	* 
	* @param len: I420 data length
	* 
	* @param yStride: y stride
	* 
	* @param uStride: u stride
	* 
	* @param vStride: v stride
	*
	* @return {0} if successful
	*/
    public native int SmartPublisherOnCaptureVideoI420Data(byte[] data, int len, int yStride, int uStride, int vStride);

Y U V三个分量的Stride信息，不是4 2 0。

如果你不确定如何填充，请加QQ 89030985.

Thanks.

**Comment by daniulive** [comment]
http://www.cnblogs.com/welhzh/p/4939613.html
请参见网上介绍。
