### ISSUE TITLE
打开SmartServicePublisher.apk异常退出

### ISSUE THREAD

**Issue by Vancezheng** [daniulive/SmarterStreaming#35]
11-14 18:03:44.555  3790  3790 D AndroidRuntime: Shutting down VM
11-14 18:03:44.557  3790  3790 E AndroidRuntime: FATAL EXCEPTION: main
11-14 18:03:44.557  3790  3790 E AndroidRuntime: Process: com.daniulive.smartpublisher, PID: 3790
11-14 18:03:44.557  3790  3790 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: libSmartPublisher.so
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at java.lang.Runtime.load0(Runtime.java:900)
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at java.lang.System.load(System.java:1505)
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at com.daniulive.smartpublisher.BackgroudService.<clinit>(BackgroudService.java:120)
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3173)
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-14 18:03:44.557  3790  3790 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
11-14 18:03:44.564  3790  3790 I Process : Sending signal. PID: 3790 SIG: 9
11-14 18:03:44.606  1540  2167 I ActivityManager: Process com.daniulive.smartpublisher (pid 3790) has died

**Comment by daniulive** [comment]
你是直接跑的demo 还是集成的时候？
还有就是，看看，是不是有获取权限了

**Comment by Vancezheng** [comment]
直接运行的demo,权限已经获取过了

**Comment by Vancezheng** [comment]
是获取完权限点击开始推流的时候崩溃的

**Comment by daniulive** [comment]
找不到so的问题在新的开发demo中已经解决了，请下载最新的安卓demo编译测试。

**Comment by Vancezheng** [comment]
试过了，这次可以用了，谢谢！
