### ISSUE TITLE
您好,请问把项目作为依赖, 出现Failed to set publish stream URL..

### ISSUE THREAD

**Issue by guoqinbo1218g** [daniulive/SmarterStreaming#39]
请问把项目作为依赖, 出现Failed to set publish stream URL..是什么原因

**Comment by daniulive** [comment]
> 未授权版本，限制app-name，如果需要集成到自己工程里面调试，可以用以下名字：
android推送端：SmartPublisherSDKDemo
android后台Service推送：SmartServicePublisherSDKDemo
android一对一互动：SmartEchoCancellation
android播放器：SmartPlayerSDKDemo
iOS推送端：SmartiOSPublisher
iOS播放器：SmartiOSPlayer
集成到自己工程，如何改名字（以推送端为例）：
android：strings.xml：
<string name="app_name">SmartPublisherSDKDemo</string>
iOS：Info.plist-->右键Open As-->Source Code，添加或者编辑
<key>CFBundleName</key>	
<string>SmartiOSPublisher</string>

**Comment by guoqinbo1218g** [comment]
好的,多谢

**Comment by daniulive** [comment]
closed
