### ISSUE TITLE
为什么没有安卓 X86 CPU架构的so呢?

### ISSUE THREAD

**Issue by momo145** [daniulive/SmarterStreaming#41]
最近在做一款rtsp直播流的演示,试了很多框架,发现你们这个框架的延时最少,很流畅,但是设备有的是X86架构的安卓平板却运行不起来,希望能提供比较全的SO支持库,这样我们就可以接入你们的sdk,可商用授权,希望能看到

**Comment by daniulive** [comment]
目前x86架构的android设备非常少，除了部分定制android设备。
我们会内部讨论是不是支持，谢谢您的建议。
如有需要，可联系QQ 89030985
