### ISSUE TITLE
h264 byte[] 推流

### ISSUE THREAD

**Issue by coderxhs** [daniulive/SmarterStreaming#46]
我们项目需要自己在andrioi service端采集视频，通过gl渲染后由MediaCodec编码之后，我们拿到的是h264格式的视频流，能否用sdk进行h264 byte[]推流呢? 应该如何修改呢，谢谢！

**Comment by daniulive** [comment]
参见我们SDK说明：
1.【最先调用】SmartPublisherOpen()：初始化SDK：
参数设置：
ctx：上下文信息；
Audio_opt: 
0：不发布audio；
1：发布audio；
2：对接外部编码后的audio数据（AAC）
video_opt:
0：不发布video；
1：发布video；
2：对接外部编码后的video数据（H.264）
宽高信息。

这里，video option传2；

2. H.264数据，通过此接口传递：
【第三方编码后数据】SmartPublisherOnReceivingVideoEncodedData()，第三方编码后视频数据接口；

具体参数参见我们SDK说明和接口。

有问题可以加我QQ 89030985 寻求对接支持。
