### ISSUE TITLE
Can not play rtsp url

### ISSUE THREAD

**Issue by vineeshtp** [daniulive/SmarterStreaming#48]
When I try to play 'rtsp' url I got the bellow error in **iOS**.
This was worked earlier.
How to resolve the issue.

[SmartPlayerSDK] Daniulive Version 2017-12-22 14:00

SmartPlayerIOS [E] [SmartPublisherSDK] SDK invalid, please refer to daniulive(QQ: 89030985,2679481035, QQ Qun:294891451) for new authorization..

SmartPlayerSDK call SmartPlayerInitPlayer failed, ret=2

**Comment by daniulive** [comment]
The version you tested is expired.
You could sent the email to 89030985@qq.com
I will send you the latest version.

BRs
