### ISSUE TITLE
Connect Local Server 

### ISSUE THREAD

**Issue by hongtou820** [daniulive/SmarterStreaming#49]
Can i connect local server ?
any example or document i can refer ?

**Comment by daniulive** [comment]
which platform do you prefer?
If possible, you only have to change the publisher/playback url.

**Comment by hongtou820** [comment]
Any document can refer to setup server in local?
This protocol is free right?

**Comment by daniulive** [comment]
You could setup Nginx-rtmp server for testing, the document from our side is based on Chinese written.
For commercial usage, it needs to pay for license.

**Comment by hongtou820** [comment]
May i know the pricing ?

**Comment by daniulive** [comment]
You could share your email address to me for license purpose.
Or you could send me the email for the module you want.
My email address 89030985@qq.com

**Comment by hongtou820** [comment]
Sent
