### ISSUE TITLE
Android - push 2 link rtmp together

### ISSUE THREAD

**Issue by bogiahatay** [daniulive/SmarterStreaming#52]
Android - i want push two link rtmp together.
1: rtmp://live-api.facebook.com:80
2: rtmp://a.rtmp.youtube.com/live2

SmarterStreaming library can do it?

**Comment by daniulive** [comment]
You mean pull 2 rtmp url, and mix the stream together?

Such as https://camo.githubusercontent.com/59201ed4c0daef3245242d352e5ca731766348bc/687474703a2f2f706c617965722e64616e69756c6976652e636f6d3a383038302f66696c65732f696d6167652f77696e646f77732f706c61796572312e706e67

**Comment by bogiahatay** [comment]
Yes. I want streaming Facebook and Youtube from android device
