### ISSUE TITLE
如何在浏览器中接入rtsp流？

### ISSUE THREAD

**Issue by sdwangbaotong** [daniulive/SmarterStreaming#53]
如题，如何在浏览器中显示rtsp的视频流？大牛的lib可以做到吗？查了下vlc的方案，目前的主流浏览器都不支持

**Comment by daniulive** [comment]
两种方案：
1. 用我们windows SDK封装activeX控件，然后在浏览器调用；
2. 我们windows/android/iOS均支持rtsp/rtmp转rtmp，有了rtmp流，在web播放就很方便了，参见 [http://daniulive.com/index.php/2018/04/04/%E5%A4%9A%E8%B7%AF%E6%B5%81%E5%AA%92%E4%BD%93%E8%BD%AC%E5%8F%91sdk/](url)
