### ISSUE TITLE
Android 推流端连接失败

### ISSUE THREAD

**Issue by PasserC** [daniulive/SmarterStreaming#56]
case EVENTID.EVENT_DANIULIVE_ERC_PUBLISHER_CONNECTION_FAILED:
                    txt = "连接失败。。";
                    break;

网络无问题，这种情况有具体log吗？或者具体的提示？都有什么情况会出现连接失败呢。

**Comment by daniulive** [comment]
你好，这个要看下具体问题，你加下qq:2679481035,  我们看下.
