### ISSUE TITLE
横屏时,显示异常

### ISSUE THREAD

**Issue by neilzhengzx** [daniulive/SmarterStreaming#58]
[_smart_publisher_sdk SmartPublisherSetPublishOrientation:publish_orientation];
在推流的展示,设备横屏,SmartPublisherSetPublishOrientation并不能使图像摆正,展示有90度的偏转,请问有什么方法可以展示正常

**Comment by neilzhengzx** [comment]
测试了demo,在把手机横向摆放,界面只剩下左边一块,人是横着显示的

**Comment by daniulive** [comment]
你可以加下我QQ 我们沟通下 89030985
