### ISSUE TITLE
CMSampleBufferRef App Audio Noise

### ISSUE THREAD

**Issue by agmoElle** [daniulive/SmarterStreaming#59]
Hi, 

When I try to stream app audio via ReplayKit, I hear nothing but noise on the feed, but when I save the buffer stream into an audio file, the audio sounds fine. 
Could this be due to audio encoding?

I use the following method after getting the sampleBuffer from processSampleBuffer callback by ReplayKit.

`-(NSInteger) SmartPublisherPostAudioSampleBuffer:(CMSampleBufferRef)data inputType:(NSInteger)inputType;`

Want to know that after I pass the data into the method, is the audio data sent as AAC or as PCM?

Thank you.

**Comment by daniulive** [comment]
Hi,

The interface of "SmartPublisherPostAudioSampleBuffer" post no-encoded audio data(PCM).

BRs.

**Comment by daniulive** [comment]
Also please make sure the publisher side is a little far away from player side, so that it could avoid the noise.

**Comment by agmoElle** [comment]
Thanks for the response.
Hmm, the distance doesn't seem to be affecting the noise, no matter how far I am away from the player side, the noise still persists.

**Comment by daniulive** [comment]
Does it possible to record the mp4 file with our app(need to integrate SmartiOSPublisherV2 record related code).

**Comment by daniulive** [comment]
the audio capture depends on the mode setting, if only publish app only, it could record app audio, otherwise it will record mic audio with background mode.
