### ISSUE TITLE
rtsp打开有点慢，加载十几秒才出画面

### ISSUE THREAD

**Issue by bifan-wei** [daniulive/SmarterStreaming#60]
rtsp打开有点慢，加载十几秒才出画面，直连摄像头数据，请问该如何配置优化

**Comment by daniulive** [comment]
你是用的什么平台的播放器？
可以加下我QQ 89030985 发log过来我们看看
我们这边，首屏只要收到第一个I帧就开始播放。。

**Comment by daniulive** [comment]
你是用的什么平台的播放器？
可以加下我QQ 89030985 发log过来我们看看
我们这边，首屏只要收到第一个I帧就开始播放。。

**Comment by bifan-wei** [comment]
加你q了

**Comment by daniulive** [comment]
摄像机只支持TCP模式，默认UDP模式尝试，达到超时时间后，尝试TCP后连接成功，可正常收数据。
这也是以下接口开放的意义：

`		//设置RTSP超时时间
		int rtsp_timeout = 10;
		libPlayer.SmartPlayerSetRTSPTimeout(playerHandle, rtsp_timeout);

		//设置RTSP TCP/UDP模式自动切换
		int is_auto_switch_tcp_udp = 1;
		libPlayer.SmartPlayerSetRTSPAutoSwitchTcpUdp(playerHandle, is_auto_switch_tcp_udp);

		// It only used when playback RTSP stream..
		// libPlayer.SmartPlayerSetRTSPTcpMode(playerHandle, 1);`

问题提的很好，其他客户有遇到过。
