### ISSUE TITLE
android 客户端最低配置？

### ISSUE THREAD

**Issue by wangxm345566462** [daniulive/SmarterStreaming#66]
酷开电视 做客户端接入 rtsp 时延迟非常高。

**Comment by daniulive** [comment]
你播放的多大分辨率帧率的流？
如果分辨率帧率过高，可以考虑硬解码。
private boolean is_enable_hardware_render_mode = true;	//设置视频硬解码下Mediacodec自行绘制模式（此种模式下，硬解码兼容性和效率更好，回调YUV/RGB和快照功能将不可用）
用直接设置surface模式的硬解码。

**Comment by daniulive** [comment]
可以加我QQ 89030985

**Comment by daniulive** [comment]
问题已处理
