### ISSUE TITLE
为何问题不能公开讨论

### ISSUE THREAD

**Issue by TangPinJia** [daniulive/SmarterStreaming#72]
想用又不敢用，感觉你们好奇怪。你们在隐藏什么。

**Comment by daniulive** [comment]
有什么问题，可以提出来。

**Comment by TangPinJia** [comment]
> 有什么问题，可以提出来。

没有哈哈，只是以前用的都会有各种各样的问题，突然看见个没问题的反而觉得奇怪哈哈，不好意思。

**Comment by daniulive** [comment]
我们这个东西做了几年了，想发现问题确实也不太容易。
我们倒是希望能帮助我们找出更多的问题或潜在问题，我们好进一步改进，谢谢你的关注。
