### ISSUE TITLE
No implementation found for long smartplayertest.SmartPlayerJniV2.SmartPlayerOpen(java.lang.Object)

### ISSUE THREAD

**Issue by EmbeddedAndMore** [daniulive/SmarterStreaming#74]
Thanks for such a great job.
I am getting this error although a have added this :
```
static {
		System.loadLibrary("SmartPlayer");
	}
```
do i need to anything else. i also aded all .so and .jar as it is in sample project.

**Comment by daniulive** [comment]
Make sure the project with our app name(or else will show "license failed" error):
strings.xml：
<string name="app_name">SmartPlayerSDKDemo</string>

IF you need license, please contact with 89030985@qq.com

1. Please make sure SmartPlayerJniV2.java put into the package name of com.daniulive.smartplayer;
2. Add Smartavengine.jar to your proeject；
3. Copy the lib "SmartPlayerV2\app\src\main\jniLibs\armeabi-v7a 
 and SmartPlayerV2\app\src\main\jniLibs\arm64-v8a“  libSmartPlayer.so to your project；
4. Load the lib:
		static {  
			System.loadLibrary("SmartPlayer");
	}
5. Add permission：
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" ></uses-permission>
<uses-permission android:name="android.permission.INTERNET" ></uses-permission>
<uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

**Comment by EmbeddedAndMore** [comment]
Oh, I thought it might be the package name.
Thanks for the quick response.
