### ISSUE TITLE
Keep aspect ratio

### ISSUE THREAD

**Issue by EmbeddedAndMore** [daniulive/SmarterStreaming#76]
Is it possible to keep the aspect ratio of the rendered stream? 

As I understand it fills all SurfaceView. but in a case with don't know the resolution we cannot set the Width and Height of the SurfaceView.

**Comment by daniulive** [comment]
Hi,

We'll notify video resolution via the event ID of "EVENT_DANIULIVE_ERC_PLAYER_RESOLUTION_INFO";

You could change the aspect ratio of the surfaceview since you have video width and height now.

`	class EventHandeV2 implements NTSmartEventCallbackV2 {
		@Override
		public void onNTSmartEventCallbackV2(long handle, int id, long param1,
				long param2, String param3, String param4, Object param5) {

			//Log.i(TAG, "EventHandeV2: handle=" + handle + " id:" + id);

			String player_event = "";

			switch (id) {
			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_STARTED:
				player_event = "开始..";
				break;
			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_CONNECTING:
				player_event = "连接中..";
				break;
			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_CONNECTION_FAILED:
				player_event = "连接失败..";
				break;
			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_CONNECTED:
				player_event = "连接成功..";
				break;
			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_DISCONNECTED:
				player_event = "连接断开..";
				break;
			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_STOP:
				player_event = "停止播放..";
				break;
			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_RESOLUTION_INFO:
				player_event = "分辨率信息: width: " + param1 + ", height: " + param2;
				break;
			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_NO_MEDIADATA_RECEIVED:
				player_event = "收不到媒体数据，可能是url错误..";
				break;
			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_SWITCH_URL:
				player_event = "切换播放URL..";
				break;
			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_CAPTURE_IMAGE:
				player_event =  "快照: " + param1 + " 路径：" + param3;

				if (param1 == 0) {
					player_event =  player_event + ", 截取快照成功";
				} else {
					player_event =  player_event + ", 截取快照失败";
				}
				break;
				
			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_RECORDER_START_NEW_FILE:
				player_event = "[record]开始一个新的录像文件 : " + param3;
                break;
            case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_ONE_RECORDER_FILE_FINISHED:
				player_event = "[record]已生成一个录像文件 : " + param3;
                break;

			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_START_BUFFERING:
				Log.i(TAG, "Start Buffering");
				break;

			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_BUFFERING:
				Log.i(TAG, "Buffering:" + param1 + "%");
				break;

			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_STOP_BUFFERING:
				Log.i(TAG, "Stop Buffering");
				break;

			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_DOWNLOAD_SPEED:
				player_event =  "download_speed:" + param1 + "Byte/s" + ", "
						+ (param1 * 8 / 1000) + "kbps" + ", " + (param1 / 1024)
						+ "KB/s";
				break;

			case NTSmartEventID.EVENT_DANIULIVE_ERC_PLAYER_RTSP_STATUS_CODE:
				Log.e(TAG, "RTSP error code received, please make sure username/password is correct, error code:" + param1);
				player_event =  "RTSP error code:" + param1;
				break;
			}

			if(player_event.length() > 0)
			{
				Log.i(TAG, player_event);
				Message message=new Message();
				message.what= PLAYER_EVENT_MSG;
				message.obj = player_event;
				handler.sendMessage(message);
			}
		}
	}`

**Comment by EmbeddedAndMore** [comment]
I found it, thanks for your quick response
