### ISSUE TITLE
react native

### ISSUE THREAD

**Issue by ciaoamigo** [daniulive/SmarterStreaming#77]
Where can I find sdk for reactnative? Is there any example?

**Comment by daniulive** [comment]
It has to pay for license fee for react native sdk.
Currently we only have player side.
For more information, you could refer to 89030985@qq.com

**Comment by ciaoamigo** [comment]
I wrote to your e-mail but received no reply ..... :(

**Comment by ciaoamigo** [comment]
Have I written several times without having an answer? Does anyone let me know something?
