### ISSUE TITLE
audio is not sending while screen sharing_ios_sampleHandler

### ISSUE THREAD

**Issue by Asadpt89** [daniulive/SmarterStreaming#80]
HI,
In iOS, while screen sharing, we need to send the audio also. but in processSampleBuffer function, we get sampleBuffer only for case:Video

**Comment by daniulive** [comment]
You can capture audio by yourself, and pass the data via our interface:

/**
 * 初始化Publisher
 *
 * <pre>此接口请第一个调用</pre>
 *
 * audio_opt和video_opt组合推送类型，如 audio_opt为1，video_opt为1，则代表推送音频和视频
 *
 * @param audio_opt
 if with 0: 不推送音频
 if with 1: 推送SDK内部采集的音频
 if with 2: 推送外部编码后音频(目前支持AAC/PCMA/PCMU/SPEEX宽带)
 if with 3: 推送外部编码前音频数据(CMSampleBufferRef类型), 数据传递对应接口: SmartPublisherPostAudioSampleBuffer
 if with 4: 推送外部采集的PCM音频
 *
 * @param video_opt
 if with 0: 不推送视频
 if with 1: 推送SDK内部采集的视频
 if with 2: 推送外部编码后视频(目前支持H.264),数据格式: 0000000167....
 if with 3: 推送外部编码前视频数据(CMSampleBufferRef类型), 数据传递对应接口: SmartPublisherPostVideoSampleBuffer
 if with 4: 推送外部编码前yuv420视频数据, 数据传递对应接口: SmartPublisherSetExternalYuvData
 if with 5: 推送外部编码前BGRA视频数据(alpha通道不使用), 数据传递对应接口: SmartPublisherSetExternalBGRAData
 if with 6: 推送外部编码前ARGB视频数据(alpha通道不使用), 数据传递对应接口: SmartPublisherSetExternalARGBData
 *
 * @return {0} if successful
 */
- (NSInteger)SmartPublisherInit:(NSInteger)audio_opt video_opt:(NSInteger)video_opt;

**Comment by ShubhGar** [comment]
I use the same but audio is not sending with screen sharing

**Comment by ShubhGar** [comment]
smartPublisherPostAudioSampleBuffer returning 1 instead of zero

**Comment by Asadpt89** [comment]
@daniulive 
we are already using that interface.
we have choosen audio_opt = 3 and video_opt = 3 in samplerHandler.

but, the smartPublisherPostAudioSampleBuffer return 1.

**Comment by Joseph7866** [comment]
SampleBuffer is returning value 1 instead of 0 for audioMic. Can you please fix this ?

**Comment by daniulive** [comment]
> rning value 1 instead of 0 for audioMic. Can

Make sure the APP layer has audio output, you could print the data or data length via NSLog at audio sample buffer part..
