### ISSUE TITLE
Flutter SDK support

### ISSUE THREAD

**Issue by abc873693** [daniulive/SmarterStreaming#81]
My school research need Flutter version to connect our RTSP camera.
Can your provide RTSP SDK for Flutter version.
This is our laboratory GitHub site.
https://github.com/NSYSU-MITLAB

**Comment by daniulive** [comment]
Currently we do not publish Flutter SDK to third-party, since we do not have enough experience in Flutter.
Maybe some day later.

**Comment by abc873693** [comment]
OK, maybe I will use native version SDK to build native view method channel plugin by myself.
Only use research.
