### ISSUE TITLE
smartPlayer（C#版）无法播放rtsp，但是vlc可以正常播放

### ISSUE THREAD

**Issue by Xianvduofengchen** [daniulive/SmarterStreaming#84]
使用的是 “Windows C#版本播放SDK Demo工程本地下载(更新于2019/08/22)”
用的vs2019社区版编译，.net 4.5.

抓包过程：(为什么OPTIONS在最后？)
c->s:
	DESCRIBE rtsp://192.168.1.28/stream1s RTSP/1.0
	CSeq: 2
	User-Agent: DNRtspClient
	Accept: application/sdp	 
s->c:
	RTSP/1.0 200 OK
	CSeq: 2
	Date: Thu, Jan 01 1970 01:09:07 GMT
	Content-Base: rtsp://192.168.1.28/stream1s/

c->s:
	SETUP rtsp://192.168.1.28/stream1s/track1 RTSP/1.0
	CSeq: 3
	User-Agent: DNRtspClient
	Transport: RTP/AVP;multicast;port=51000-51001
s->c:
	RTSP/1.0 200 OK
	CSeq: 3
	Date: Thu, Jan 01 1970 01:09:07 GMT
	Transport: RTP/AVP;multicast;destination=232.155.52.34;source=192.168.1.28;port=51000-51001;ttl=5
	Session: 61B3E7A4

c->s:
	PLAY rtsp://192.168.1.28/stream1s/ RTSP/1.0
	CSeq: 4
	User-Agent: DNRtspClient
	Session: 61B3E7A4
	Range: npt=0.000-
s->c:
	RTSP/1.0 200 OK
	CSeq: 4
	Date: Thu, Jan 01 1970 01:09:07 GMT
	Range: npt=0.000-
	Session: 61B3E7A4
	RTP-Info: url=rtsp://192.168.1.28/stream1s/track1;seq=48384;rtptime=4147270

c->s:
	OPTIONS rtsp://192.168.1.28/stream1s/ RTSP/1.0
	CSeq: 5
	User-Agent: DNRtspClient
	Session: 61B3E7A4
s->c:
	RTSP/1.0 200 OK
	CSeq: 5
	Date: Thu, Jan 01 1970 01:09:47 GMT
	Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, SET_PARAMETER

**Comment by daniulive** [comment]
DESCRIBE返回的SDP信息贴一下，我们看看audio video格式是不是支持
或加我QQ 89030985

**Comment by Xianvduofengchen** [comment]
RTSP/1.0 200 OK
CSeq: 2
Date: Thu, Jan 01 1970 01:23:32 GMT
Content-Base: rtsp://192.168.1.28/stream1s/
Content-Type: application/sdp
Content-Length: 431


v=0
o=- 26278752 1 IN IP4 192.168.1.28
s=Session streamed by "ASX RTSP Server"
i=live stream1s
t=0 0
a=tool:LIVE555 Streaming Media v2010.02.10
a=type:broadcast
a=control:*
a=source-filter: incl IN IP4 * 192.168.1.28
a=rtcp-unicast: reflection
a=range:npt=0-
a=x-qt-text-nam:Session streamed by "ASX RTSP Server"
m=video 51000 RTP/AVP 96
c=IN IP4 232.155.52.34/255
b=AS:2500
a=rtpmap:96 H264/1000
a=control:track1





------------------ 原始邮件 ------------------
发件人: "daniulive"<notifications@github.com>;
发送时间: 2019年9月23日(星期一) 中午11:32
收件人: "daniulive/SmarterStreaming"<SmarterStreaming@noreply.github.com>;
抄送: "华"<804944224@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [daniulive/SmarterStreaming] smartPlayer（C#版）无法播放rtsp，但是vlc可以正常播放 (#84)




DESCRIBE返回的SDP信息贴一下，我们看看audio video格式是不是支持
 或加我QQ 89030985

**Comment by daniulive** [comment]
数据问题。。
09-23 11:46:07.035 [00003f0c] <error> [SP] VDec input packet data failed
09-23 11:46:07.995 [00003f0c] <error> [SP] VDec input packet data failed
09-23 11:46:08.995 [00003f0c] <error> [SP] VDec input packet data failed
09-23 11:46:10.005 [00003f0c] <error> [SP] VDec input packet data failed
09-23 11:46:10.995 [00003f0c] <error> [SP] VDec input packet data failed
09-23 11:46:12.005 [00003f0c] <error> [SP] VDec input packet data failed
09-23 11:46:13.005 [00003f0c] <error> [SP] VDec input packet data failed
09-23 11:46:14.001 [00003f0c] <error> [SP] VDec input packet data failed
09-23 11:46:15.001 [00003f0c] <error> [SP] VDec input packet data failed
09-23 11:46:16.001 [00003f0c] <error> [SP] VDec input packet data failed
09-23 11:46:17.001 [00003f0c] <error> [SP] VDec input packet data failed
09-23 11:46:17.996 [00003f0c] <error> [SP] VDec input packet data failed
