### ISSUE TITLE
iOS ReplayKit demo 更新

### ISSUE THREAD

**Issue by coderchou** [daniulive/SmarterStreaming#86]
**SmartiOSScreenPublisherV2**  demo工程很旧了吧，这种方式目前只支持应用内屏幕录制，**APP**进入后台录制就断了，能不能支持**iOS 12**以上系统 ，增加对 **RPSystemBroadcastPickerView** 的支持，谢谢

**Comment by daniulive** [comment]
加我QQ 89030985 我发给你个新版的，下个release会发出去。。

**Comment by coderchou** [comment]
非常感谢
