### ISSUE TITLE
SmartPlayerSDK 提供暂停播放的方法

### ISSUE THREAD

**Issue by coderchou** [daniulive/SmarterStreaming#87]
**SmartPlayerSDK** 能否提供一个暂停播放的方法，有时直播页面需要播放其他的音频或者视频，需要暂停掉直播，目前采取的方式是销毁掉**SmartPlayerSDK**，需要直播时重新初始化**SmartPlayerSDK**，很不方便

**Comment by daniulive** [comment]
直播流 一般来说不存在暂停的概念
比如，暂停的时候，如果只是不解码绘制的话，数据还在正常下载，占用带宽流量，意义不大。。

**Comment by coderchou** [comment]
了解，但还是有这个痛点
