### ISSUE TITLE
您好，请问下视频推流 windows 版支持命令行吗

### ISSUE THREAD

**Issue by potoo0** [daniulive/SmarterStreaming#91]
您好，请问下视频推流 windows 版支持命令行吗，类似 ffmpeg 的命令行方式？
我现在想做的是 rtmp 推流 h265，但是源画面是 python 处理的，所以想 python 多进程打开命令行管道传图片，ffmpeg 支持命令行，但是 目前 ffmpeg 官网 release 版本不支持 h265 写到 flv。

**Comment by daniulive** [comment]
我们没有命令行版本，谢谢。。

**Comment by potoo0** [comment]
好的，谢谢啦。
