### ISSUE TITLE
URL解析问题

### ISSUE THREAD

**Issue by non0** [daniulive/SmarterStreaming#92]
例如：SetURL传入rtsp://admin:admin@2020@192.168.2.34/stream密码中带有“@”符号的会解析出错

**Comment by daniulive** [comment]
相关SPEC有说明，这个地方，不能有特殊字符。

**Comment by non0** [comment]
试过其他库解释这样的url并没有问题，如libvlc等，希望改进一下！

**Comment by fengyu999** [comment]
+1，这种带@的url可以解析吗？
