### ISSUE TITLE
tested Smartplayer.apk but failed to show video

### ISSUE THREAD

**Issue by netist123** [daniulive/SmarterStreaming#96]
首先设置的rtmp url 没问题。
点播放后可以看到连接成功，并且有下载速率动态显示，表示应该已经工作了。
但是视频无法显示出来。
界面还是停留在配置页。
点快照，点录像也都没有任何作用。

android 9.

**Comment by daniulive** [comment]
你把你的url，单独发给我下，我们帮你看下，加我QQ 89030985

**Comment by daniulive** [comment]
如我们沟通，音频: MP3，视频 FLV1格式，咱们SDK不支持。
