### ISSUE TITLE
个别设备  SmartPlayerOpen 方法返回值为0 初始化失败

### ISSUE THREAD

**Issue by waitinghu** [daniulive/SmarterStreaming#97]
playerHandle = libPlayer.SmartPlayerOpen(myContext);

        if (playerHandle == 0) {
            Log.e(TAG, "surfaceHandle with nil..");
            return;
        }
playterHandle 总是等于0,请问这是什么原因?

**Comment by daniulive** [comment]
你好，可以加qq:2679481035发日志看下.

**Comment by jenlyser** [comment]
我也遇到相同问题,解决了吗?

**Comment by jenlyser** [comment]
> 我也遇到相同问题,解决了吗?

我看了一下日志,是需要授权. SDK invalid, please refer to daniulive for new authorization..

**Comment by daniulive** [comment]
> > 我也遇到相同问题,解决了吗?
> 
> 我看了一下日志,是需要授权. SDK invalid, please refer to daniulive for new authorization..

是用的版本比较老，SDK过期了，每个版本大概1-2个月的时效，具体你可以加我QQ 89030985
