### ISSUE TITLE
建议包工程按照iOS，Android，Windows...拆分一下

### ISSUE THREAD

**Issue by hawskpy** [daniulive/SmarterStreaming#99]
建议包工程按照iOS，Android，Windows...拆分一下，我想下一个平台的工程 我所有都要下载下来，包太大，下载太慢了 泪崩啊~

**Comment by daniulive** [comment]
考虑到这点，我们有本地下载链接：
readme往下拉：

**本地下载**

很多开发者反应，由于项目庞大，github下载整个工程很慢，我们已经把相关demo文件和使用说明，全部上传到QQ群共享：

 大牛直播技术交流群3(推荐加入): 182979815

 大牛直播技术交流群2(即将满员): 294891451

 大牛直播技术交流群1(已满): 499687479

或者直接从私有服务器下载(Windows提供C#/C++ demo, android提供android studio demo，iOS提供xcode demo)：

**Comment by daniulive** [comment]
已采纳，谢谢你的建议，Windows版本之前就是拆分的，最新发布的iOS的版本，已经拆分了。
